[WIP] Lazy expression service
dart-lang/webdev pull request #1222
Opened 2021-01-12 22:45 UTC by grouma

2021-01-13 00:36 UTC, grouma commented
cc @nshahan the next step is to read the metadata files and look for the corresponding null safety support boolean.

2021-01-13 00:52 UTC, nshahan commented
The change that adds the null safety boolean is going through the commit queue now and should land any minute. 
https://dart-review.googlesource.com/c/sdk/+/178161

2021-01-14 19:17 UTC, annagrin requested changes

2021-01-14 19:17 UTC, annagrin commented on dwds/lib/src/services/expression_compiler_service.dart
> +  Future<void> initialize({bool withNullSafety}) async {
We need to have an option to pass platform files for google3, currently ddr_handler computes all parameters for startWithPlatform and calls it directly. Maybe add them to the constructor instead of computing here, and have a one constructor with the default values below?

2021-01-14 19:17 UTC, annagrin commented on dwds/lib/src/services/expression_compiler_service.dart
> +  static Future<_Compiler> startWithPlatform(
need to pass `soundNullSafety` as a parameter to this, and add  `--sound-null-safety` option to the args if it is true

2021-01-14 19:17 UTC, annagrin commented on dwds/lib/src/services/expression_compiler_service.dart
> +    var compiler = await _Compiler.startWithPlatform(_address, _port,
can just be renamed to `start`

2021-01-14 19:17 UTC, annagrin commented on dwds/lib/src/services/expression_compiler_service.dart
> +  static Future<_Compiler> startWithPlatform(
I think we can rename this method to `start` since there will be only one

2021-01-14 23:50 UTC, annagrin approved these changes
LGTM (with a small change). Thanks!

2021-01-14 23:50 UTC, annagrin commented on dwds/lib/src/services/expression_compiler_service.dart
> +      if (soundNullSafety) '--sound-null-safety',
I am not sure what the default mode of ddc is, so if we want to be safe,  this should be `soundNullSafety? '--sound-null-safety': '--no-sound-null-safety'`

2021-01-15 23:16 UTC, merged