Show a warning in the Dart Debug Extension when a user tries to debug a sharded Dart app
dart-lang/webdev pull request #1462
Opened 2021-12-07 01:00 UTC by elliette

When we detect that a Dart application is sharded, the Dart Debug Extension turns red. Clicking on it will open the following alert:
![Screen Shot 2021-12-06 at 4 51 22 PM](https://user-images.githubusercontent.com/21270878/144946744-15d4e789-ff29-4ee3-b5c2-0a3ffb673f96.png)

2021-12-07 01:54 UTC, annagrin reviewed
Thanks Elliott!

To make sure we track the change in our published versions correctly, could you please:
- add a test - maybe `dwds/test/debug_extension_test.dart`can help?
- add a CHANGELOG.md message
- could you please update the version in pubspec.yaml to the new dev version (ie 11.5.1-dev)
- run `dart run build_runner build` in dwds directory (using the latest dart, I normally use the latest dev but stable is ok too)

2021-12-08 17:12 UTC, elliette commented
Everything should be updated now, thanks!

2021-12-08 23:22 UTC, annagrin requested changes
Looks great! Just a few minor comments...

2021-12-08 23:22 UTC, annagrin commented on dwds/CHANGELOG.md
> +- Show an alert in the Dart Debug Extension for a multi-app scenario
Nit: this should be a complete sentence, like comments - ie starting with a capital letter and ending with a period.

2021-12-08 23:22 UTC, annagrin commented on dwds/pubspec.yaml
> +version: 11.5.0-dev.1
This should be 11.5.1-dev (that precedes 11.5.1)

2021-12-08 23:22 UTC, annagrin commented on dwds/test/debug_extension_test.dart
> +          await Future.delayed(const Duration(seconds: 2));
I know that this happens in other tests, but waiting without checking the status might introduce flakes that are hard to debug - is there a way to periodically test the attribute change and continue after it is set, or fail the test after a few attempts?

2021-12-09 19:14 UTC, elliette commented on dwds/CHANGELOG.md
> +- Show an alert in the Dart Debug Extension for a multi-app scenario
Done, thanks!

2021-12-09 19:14 UTC, elliette commented on dwds/pubspec.yaml
> +version: 11.5.0-dev.1
Done

2021-12-09 19:15 UTC, elliette commented on dwds/test/debug_extension_test.dart
> +          await Future.delayed(const Duration(seconds: 2));
Looks like this wait can be removed, but added a retry wrapper around the other one.

2021-12-10 18:22 UTC, annagrin approved these changes
LGTM!

2021-12-10 19:02 UTC, merged