Add IDE workspace configuration directories to the `gitignore`
dart-lang/webdev pull request #1477
Opened 2021-12-21 18:13 UTC by elliette

Adds the workspace configuration directories for IntelliJ and VSCode.

2022-01-07 19:07 UTC, annagrin requested changes

2022-01-07 19:07 UTC, annagrin commented on .gitignore
> +.idea/
Our guidelines are to avoid committing global ignores for personal workflow setup files (See: https://www.dartlang.org/guides/libraries/private-files)

You can do it locally on your machine:

~/.gitconfig:
```
# This is Git's per-user configuration file.
[user]
        name = ...
...
[core]
        excludesfile = /Users/<username>/.gitignore
```

and ~/.gitignore:
```
# See https://www.dartlang.org/guides/libraries/private-files

# Files and directories created by VSCode
.vscode/
```

2022-01-10 18:13 UTC, elliette commented on .gitignore
> +.idea/
Got it, thanks! Will close this PR then.

2022-01-10 18:13 UTC, closed without merging

2022-01-10 18:51 UTC, annagrin commented on .gitignore
> +.idea/
thanks!