Add option to launch DevTools in the same Chrome window
dart-lang/webdev pull request #1481
Opened 2021-12-23 23:45 UTC by elliette

A few customers requested the ability to launch Dart DevTools in the same Chrome window as their Dart application. Currently we only launch Dart DevTools from a different Chrome window, this adds the ability to launch it from the same window.

2022-01-07 19:26 UTC, annagrin requested changes
This is a breaking change so we need to update the version and changelog - left comments inside.

2022-01-07 19:26 UTC, annagrin commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
This needs a major version change - as this is the API used by Flutter tools and DDR to start dwds. Could you please update the version, add changelog comments and rebuild?

2022-01-07 19:29 UTC, annagrin commented
FYI - the test failure could be causes by the bad DDS update that we encountered last week. It should be fixed now, so rerunning the tests might help.

2022-01-10 18:21 UTC, annagrin commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
Actually, since the 12.0.0-dev is still in the baking, we can keep the version as is, we only need the breaking change recorded in the changelog.

2022-01-10 18:45 UTC, elliette commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
Ok sg! Updated the CHANGELOG

2022-01-10 18:54 UTC, annagrin requested changes
One more thing...

2022-01-10 18:54 UTC, annagrin commented on dwds/CHANGELOG.md
> +  - Add an option to launch Dart DevTools in the same window as the connected Dart app.
Since it is a breaking change, could you please move it to the section below and describe it as an additional parameter to dwds.start?

2022-01-11 01:24 UTC, annagrin commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
I wonder if the change got lost in the merge, I cannot see it...

2022-01-11 17:56 UTC, elliette commented on dwds/CHANGELOG.md
> +  - Add an option to launch Dart DevTools in the same window as the connected Dart app.
Moved it to the section below and updated the comment!

2022-01-11 17:57 UTC, elliette commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
Hmm which change can't you see?

2022-01-11 20:06 UTC, annagrin commented on dwds/lib/dwds.dart
> +    bool launchDevToolsInNewWindow,
Nm, i see it now.

2022-01-11 20:07 UTC, annagrin approved these changes
LGTM!

2022-01-11 23:21 UTC, merged