Migrate `.packages` to `package_config`
dart-lang/webdev pull request #1537
Opened 2022-03-10 20:41 UTC by elliette

See https://github.com/dart-lang/webdev/issues/1526

2022-03-10 21:34 UTC, annagrin commented
Thanks Elliott! It looks like the tests are failing because more .packages files are used in frontend_server_common packages as well (it is used for evaluation testing to set up frontend server similar to what flutter_tools does).

2022-03-10 21:36 UTC, annagrin requested changes
Thanks Elliott! frontend_server_common package is also using .packages files, you would need to change those as well (used in test setup, so it causes the tests to fail)

2022-03-17 20:22 UTC, grouma approved these changes

2022-03-18 23:12 UTC, annagrin commented
@elliette I have a draft that fixes fronted_server_common issue (mapping of file paths to uri's was done using .packages, changed it to use package_config).

2022-03-22 21:04 UTC, closed without merging