Convert JavaScript uncaught exception stack traces to Dart stacks
dart-lang/webdev pull request #1603
Opened 2022-05-10 00:43 UTC by jason-simmons

See https://github.com/dart-lang/webdev/issues/1265
See https://github.com/flutter/flutter/issues/101888

2022-05-10 19:40 UTC, jason-simmons commented
Added a test

2022-05-10 23:40 UTC, annagrin requested changes
Thanks Jason! Left some comments to cover more cases.

There are a few things we need to do:

- address CR comments
- update dwds version to `14.0.2-dev` in  `changelog.md` and pubspec.yaml (`14.0.1` is in the making right now, so changing to `14.0.2-dev` would be the easiest to resolve conflicts)
- add a description of the fix to the `changelog.md`
- run `dart run build_runner build`
- commit and submit your changes

2022-05-10 23:40 UTC, annagrin commented on dwds/lib/src/services/chrome_proxy_service.dart
> +        exceptionsSubscription =
I tried this change in VSCode and noticed that it still shows traces when paused on exception. 

We need to use the same translation in another place: https://github.com/dart-lang/webdev/blob/5a109f4d874604a64ec3482df5f3d9ec1837d2c3/dwds/lib/src/debugging/debugger.dart#L562

 I suggest moving out the mapping code into the `inspector.dart` and calling it from both `chrome_proxy_server.dart` and `debugger.dart`, and making `jsCallFunction` private again. 

Also, we need to make sure to cover the VSCode case with a test - maybe add a test that runs code that throws dart exception, waits for pause event, and makes sure there is no JS  code in the inside the pause event?

You can see examples on how to subscribe to the debug event stream in https://github.com/dart-lang/webdev/blob/5a109f4d874604a64ec3482df5f3d9ec1837d2c3/dwds/test/chrome_proxy_service_test.dart#L921

And how to wait for pause in https://github.com/dart-lang/webdev/blob/5a109f4d874604a64ec3482df5f3d9ec1837d2c3/dwds/test/chrome_proxy_service_test.dart#L930 (use `kPauseException` instead of `kPauseBreakpoint`)

2022-05-10 23:42 UTC, annagrin commented
Thanks Jason!

Let me know if you would like to me to take over at any point if it gets too complicated.

2022-05-12 00:41 UTC, jason-simmons commented
Added handling for the VSCode case, and a check in an existing test for stack trace mapping on an exception pause event.

PTAL

2022-05-13 21:54 UTC, annagrin commented
Thanks Jason, this is fantastic! Merging with master should resolve the test failures (you might need to update the version to 14.0.3-dev and rerun `dart run build_runner build`, since the master version has updated).

2022-05-16 22:17 UTC, jason-simmons commented
I rebased this on master and it's passing CI now.

However, when I run `dart run build_runner build` it modifies various JavaScript files that look unrelated.  In particular, the output seems to be undoing some of the changes that were made by https://github.com/dart-lang/webdev/commit/8426dc5d5ff63efd360db7ca4bcc55a380792a9b

Should I add the build_runner output to this PR, or can the PR be landed as is?  Or do I need to do something else (such as running build_runner with a different version of the Dart SDK)?

2022-05-17 23:54 UTC, annagrin commented
I am not sure what's happening, could be that your dart version is not the same as Elliott's, or some packages are outdated. I'll try to fix that part and append to your PR.

2022-05-18 00:01 UTC, annagrin commented
@jason-simmons I build your PR and it seems to not generate anything bad, just some changes in the compiled `client.js` due to latest changes in dart2js. LGTM to check this in after the test pass!

2022-05-18 00:02 UTC, annagrin approved these changes
LGTM! Thank you Jason for your contribution!

2022-05-18 16:54 UTC, merged