Update method signature of `lookupResolvedPackageUris`
dart-lang/webdev pull request #1633
Opened 2022-06-01 21:59 UTC by elliette

See: https://github.com/dart-lang/webdev/issues/1632

2022-06-01 22:57 UTC, annagrin commented on dwds/lib/src/services/chrome_proxy_service.dart
> +  Future<UriList> lookupResolvedPackageUris(String isolateId, List<String> uris,
Do we need to update vm_service version to match?

2022-06-01 23:09 UTC, annagrin requested changes

2022-06-01 23:09 UTC, annagrin commented on dwds/lib/src/services/chrome_proxy_service.dart
> +  Future<UriList> lookupResolvedPackageUris(String isolateId, List<String> uris,
@bkonyi I found this PR in dart SDK introducing the change but it does not update the vm_service package version - am I right that we need to add a constraint to this PR to depend on that min version  to prevent webdev users from pulling new dwds with old vm_service?

2022-06-01 23:18 UTC, annagrin commented on dwds/lib/src/services/chrome_proxy_service.dart
> +  Future<UriList> lookupResolvedPackageUris(String isolateId, List<String> uris,
@bkonyi if you would like to update the version later I think it is ok but we cannot publish dwds until that happens and we add the constraint. @elliette  still can submit this PR I think, and both vm_service and dwds would be unpublished versions in g3 until then. I hope that I am not wrong:)

2022-06-01 23:20 UTC, annagrin approved these changes
LGTM (if we confirm that checking this in and not publishing until vm_service version update and adding the constraint is ok.)

2022-06-01 23:27 UTC, annagrin commented on dwds/lib/src/services/chrome_proxy_service.dart
> +  Future<UriList> lookupResolvedPackageUris(String isolateId, List<String> uris,
@bkonyi  addition - I believe it should be a major version update for vm_service for this all to work out.

2022-06-02 14:09 UTC, bkonyi commented
Yeah, we'll need to publish `package:vm_service` `9.0.0` (I can't believe we're hitting double digits on the major revision already...).

2022-06-02 16:45 UTC, elliette commented
Update on this: we're going to hold off on submitting it until the `package:vm_service` version `9.0.0` has been released. Then will update the VM service min constraint and submit, followed by publishing DWDS and Webdev.

2022-06-23 22:29 UTC, merged