Bump package:vm_service to ^12.0.0
dart-lang/webdev pull request #2248
Opened 2023-10-11 21:19 UTC by bkonyi

2023-10-11 22:43 UTC, elliette commented on dwds/pubspec_overrides.yaml
I don't think we want to delete this - we always using the `package:vm_service` from head during development (and remove it when we do the release)

2023-10-11 22:45 UTC, elliette requested changes
Thank you! Do you mind also updating the CHANGELOG? (You can modify the existing line `Update the interface for ChromeProxyService.getSourceReport to match the VM service` to include the version)

2023-10-12 14:20 UTC, bkonyi commented on dwds/pubspec_overrides.yaml
Whoops, I thought this was a temporary fix. Restored.

2023-10-13 18:26 UTC, elliette approved these changes

2023-10-13 18:27 UTC, merged