Yj dartdevembedder 2488
dart-lang/webdev pull request #2531
Opened 2024-11-29 21:50 UTC by jyameo

- Refactored LoadStrategyHandler to streamline JS generation and added support for
the dartDevEmbedder API for methods: getObjectMetadata, getObjectFieldNames, getSubRange, and getFunctionMetadata - [#2488](https://github.com/dart-lang/webdev/issues/2488)
- Reenabled tests in frontend_server_ddc_and_canary_evaluate_test.dart. - [#2488](https://github.com/dart-lang/webdev/issues/2488)

2024-12-02 19:00 UTC, srujzs requested changes
Thanks Jessy! Looks like that test is passing, nice work!

We should look into getting some other tests working with the library bundle format so we can test other debugger APIs but I'm guessing you're already aware of that. :)

2024-12-02 19:00 UTC, srujzs commented on dwds/CHANGELOG.md
> +- Added LoadStrategyHandler to streamline JS expression generation and added support for
This is a bit too descriptive for a changelog entry imo. I'd only put stuff that users of this package will be affected by (what tests are run is probably only useful for us :)). Perhaps:

```
- Added support for some debugging APIs with the DDC library bundle format.
```

2024-12-02 19:00 UTC, srujzs commented on dwds/lib/src/debugging/inspector.dart
> +    final expression = LoadStrategyHandler(globalToolConfiguration.loadStrategy)
Instead of creating a new instance every time, we may want to cache it in the `LoadStrategy` itself as a final field e.g. `final dartRuntimeDebugger = DartRuntimeDebugger(this);` and use that everywhere.

2024-12-02 19:00 UTC, srujzs commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +// Copyright (c) 2024, the Dart project authors.
nit: the wrapping is inconsistent with other files.

2024-12-02 19:00 UTC, srujzs commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +class LoadStrategyHandler {
`LoadStrategyHandler` doesn't tell us much about its purpose. Maybe something like `DartRuntimeDebugger`?

2024-12-02 19:00 UTC, srujzs commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +  String _generateJsExpression(
We're losing information by taking in an arbitrary `LoadStrategy` and then reconstructing that information with the `id` check here.

One suggestion is to separate this class into two implementations, one for the existing DDC runtime, and the other one for the new library bundle runtime (and one class for the base abstract class). Then the specific `LoadStrategy` can pick the one that is relevant. The pro of this is that we don't have to do this branching logic. The con is that now you have debugging calls in two different places, but keeping the classes in the same file should mitigate that and even allow you to possibly reuse any private members if needed.

If we think that's uglier, then we should at least encode this logic into a final boolean field e.g. `final bool useLibraryBundleExpression;` so we're not always recomputing it.

2024-12-02 21:17 UTC, jyameo commented on dwds/CHANGELOG.md
> +- Added LoadStrategyHandler to streamline JS expression generation and added support for
Agreed, thanks for the suggestion! I'll update the changelog accordingly.

2024-12-02 21:17 UTC, jyameo commented on dwds/lib/src/debugging/inspector.dart
> +    final expression = LoadStrategyHandler(globalToolConfiguration.loadStrategy)
Good point!

2024-12-02 21:18 UTC, jyameo commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +class LoadStrategyHandler {
I agree. DartRuntimeDebugger is a much clearer and more descriptive name.

2024-12-02 22:05 UTC, jyameo commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +  String _generateJsExpression(
I like the `useLibraryBundleExpression` approach. Instead of always recomputing the `id`, I initialize this field in the constructor based on the `runtimeType`. It keeps the logic simple and avoids duplication while still being efficient. What do you think?

2024-12-02 22:08 UTC, jyameo reviewed
@srujzs I have the changes left in the PR. Please let me know if more changes are needed

2024-12-02 22:41 UTC, srujzs commented on dwds/lib/src/loaders/dart_runtime_debugger.dart
> +            _loadStrategy.runtimeType == DdcLibraryBundleStrategy;
`runtimeType` should rarely be used outside of debugging. It's brittle, and an `is` check would accomplish what you want here anyways.

That being said, I'd instead have this boolean be a parameter to the constructor and use named parameters e.g.

```dart
DartRuntimeDebugger({required LoadStrategy loadStrategy, required bool useLibraryBundleExpression}) : _loadStrategy = loadStrategy, _useLibraryBundleExpression = useLibraryBundleExpression;
```

(I avoid using `this.loadStrategy` and `this.useLibraryBundleExpression` to avoid making these fields public)

2024-12-02 22:41 UTC, srujzs commented on dwds/lib/src/loaders/ddc.dart
> +    _dartRuntimeDebugger = DartRuntimeDebugger(this);
I believe if you put this in the initializer list instead of giving this constructor a body, you don't need the `late` above. (same comment in the `ddc_library_bundle.dart` file)

2024-12-02 22:41 UTC, srujzs commented on dwds/lib/src/loaders/ddc.dart
> +  DartRuntimeDebugger get dartRuntimeDebugger => _dartRuntimeDebugger;
Does this need to be a getter instead of just making the final field public? I don't know why we do different things for `buildSettings` and `reloadConfiguration`, but the `reloadConfiguration` way is more concise and has fewer members. :) You can also just have the initialization directly in the member e.g. `final DartRuntimeDebugger dartRuntimeDebugger = DartRuntimeDebugger(...);`. (same comment in the `ddc_library_bundle.dart` file)

2024-12-02 22:41 UTC, srujzs commented on dwds/lib/src/loaders/dart_runtime_debugger.dart
> +// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
What are your thoughts on putting this file in `lib/src/debugging` instead?

2024-12-02 22:42 UTC, srujzs commented on dwds/lib/src/loaders/load_strategy_handler.dart
> +  String _generateJsExpression(
I think the approach is okay, but we should avoid using `runtimeType`.

2024-12-03 16:35 UTC, jyameo commented on dwds/lib/src/loaders/dart_runtime_debugger.dart
> +            _loadStrategy.runtimeType == DdcLibraryBundleStrategy;
makes sense! Thanks

2024-12-03 16:35 UTC, jyameo commented on dwds/lib/src/loaders/ddc.dart
> +    _dartRuntimeDebugger = DartRuntimeDebugger(this);
unfortunately this doesn't seem possible since `this` is only available after the initialization phased therefore I get an `Invalid reference to this` if I try to access it in the initialization list.

2024-12-03 16:35 UTC, jyameo commented on dwds/lib/src/loaders/ddc.dart
> +  DartRuntimeDebugger get dartRuntimeDebugger => _dartRuntimeDebugger;
I moved initialization of `_dartRuntimeDebugger` to a member field. Using `late final` ensures `_dartRuntimeDebugger` is lazily initialized and assigned only once, guaranteeing immutability. I kept the getter to enforce that `LoadStrategy` subclasses must override it, ensuring they provide an implementation. This also keeps access control consistent with other fields.  What do you think?

2024-12-03 16:35 UTC, jyameo commented on dwds/lib/src/loaders/dart_runtime_debugger.dart
> +// Copyright (c) 2024, the Dart project authors.  Please see the AUTHORS file
I think it make sense to have it there with the other "debuggers".

2024-12-03 17:45 UTC, srujzs approved these changes
LGTM % my final comment. Thanks for the edits!

2024-12-03 17:45 UTC, srujzs commented on dwds/lib/src/loaders/ddc.dart
> +  DartRuntimeDebugger get dartRuntimeDebugger => _dartRuntimeDebugger;
> I kept the getter to enforce that LoadStrategy subclasses must override it, ensuring they provide an implementation. This also keeps access control consistent with other fields. What do you think?

We definitely need an abstract getter like you have in `LoadStrategy`, but the implementations can just use `late final` fields to override the getter e.g.

```dart
abstract class A {
  A get a;
}

class B extends A {
  @override
  late final A a = this;
}

class C extends B {
  @override
  A get a => this;
}

void main() {
  print(B().a); // Instance of 'B'
  print(C().a); // Instance of 'C'
}
```

We don't need the separate getter to override the abstract getter, a `final` field can do it with an `@override` annotation (which isn't necessary, but the linter might complain and it's good practice).

2024-12-03 17:46 UTC, srujzs commented on dwds/lib/src/loaders/ddc.dart
> +    _dartRuntimeDebugger = DartRuntimeDebugger(this);
Right, `this` requires `late`. Shows how little I know about `late` initialization. :D

2024-12-03 18:11 UTC, jyameo commented on dwds/lib/src/loaders/ddc.dart
> +  DartRuntimeDebugger get dartRuntimeDebugger => _dartRuntimeDebugger;
Got it, thanks for clarifying! I see now that I was missing the @override annotation, which is why I was getting some linter complaints. This approach definitely keeps things cleaner and more concise. Appreciate the example!

2024-12-03 18:27 UTC, jyameo commented
@srujzs what do you think about renaming the test `frontend_server_ddc_and_canary_evaluate_test` to `frontend_server_library_bundle_evaluate_test`?

2024-12-03 20:31 UTC, srujzs approved these changes

2024-12-03 20:32 UTC, srujzs commented
> what do you think about renaming the test frontend_server_ddc_and_canary_evaluate_test to frontend_server_library_bundle_evaluate_test?

Talked offline but, `frontend_server_ddc_library_bundle_evaluate_test` SGTM.

2024-12-03 20:47 UTC, merged